server:
  port: 9090
spring:
  application:
    name: booking-api
  datasource:
    url: jdbc:mysql://bjiwgii26ti6lhkxncrd-mysql.services.clever-cloud.com/bjiwgii26ti6lhkxncrd
    username: u6r9g3vnweca6gen
    password: iJ3aJR98ME771CGOuoEv

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

