server:
  port: 9090
spring:
  application:
    name: booking-api
  datasource:
    url: jdbc:mysql://n76.h.filess.io:3306/lodgingService_sickbasket
    username: lodgingService_sickbasket
    password: 4dd1707c680f6a827c0fd0566274c7c31bc75cb1
    hikari:
      maximum-pool-size: 2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

