version: "3.3"
services:
  app:
      image: bautionorato/lodging_api:1.0.0
      ports:
        - "9090:9090"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/bookingApi-dev
        SPRING_DATASOURCE_USERNAME: 'usr-bookingApi'
        SPRING_DATASOURCE_PASSWORD: 'pwd-bookingApi'
      depends_on:
        - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: 'bookingApi-dev'
      MYSQL_USER: 'usr-bookingApi'
      MYSQL_PASSWORD: 'pwd-bookingApi'
        
      MYSQL_ROOT_PASSWORD: 'pwd-bookingApi'
    ports:
      - '3307:3307'
    expose:
      - '3307'