server:
  port: 9090
spring:
  application:
    name: booking-api
  datasource:
    url: jdbc:mysql://bk6n1nyqilwe0zoonhkr-mysql.services.clever-cloud.com/bk6n1nyqilwe0zoonhkr
    username: urq6mktznf9t4i7f
    password: jPPxSbsChva0P65rkBo8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

